[package]
name = "nathello"
version = "0.1.0"
authors = ["wantlord"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "*"

[lib]
name = "nathello"
crate-type = ["cdylib"]
